# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
#Per obrir phpmyadmin localhost:8080 server:mariadb username:bn_myapp

version: '2'

services:
  mariadb:
    container_name: mariadb_2
    image: docker.io/bitnami/mariadb:11.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=M7_UF2_db
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      #Tenia 8000:8000 pero em donava error de ports
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=M7_UF2_db
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_2
    ports:
      - 8080:80
    environment:
     # - PMA_ARBITRARY=1
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password